name_or_path: Salesforce/codet5-base
logging_dir: <root>/data/proofsteps/training_results/logs/model
model_args:
  no_init_eval: True
  padding: True
  truncation: True
  max_seq_length: 2048
  max_length: 2048
  load_model: True
  use_lora: False
  is_seq2seq: True # T5 is a sequence to sequence model
  token:
  comet_experiment: