training_data_dir: /mnt/sdd1/<root>/data/compcert/train/20240105-021649/
training_meta_filename: local.meta.json
training_data_log_dir: .log/run_training/logs/dataset_logs
training_dataset_type: CopraTrainingDataset
training_data_formatter_type: CopraPromptTrainingDataFormatter
training_dataset_args:
  system_prompt_file: src/thrall_lib/data/prompts/system/copra-coq-dfs.md
  conversation_prompt_file: src/thrall_lib/data/prompts/conversation/copra-coq-dfs.md
  characters_per_token: 4.2
  max_tokens: 4096
eval_data_dir: /mnt/sdd1/<root>/data/compcert/test/20240105-021512/
eval_meta_filename: local.meta.json
eval_data_log_dir: .log/run_training/logs/dataset_logs
test_data_dir: 
test_meta_filename: 
test_data_log_dir: 